version: "3"
services:
  postgres:
    image: library/postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
